name: Build and Publish nightly package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-python

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Install dependencies
        run: |
          apt-get update -qq
          apt-get install -yqq tea-pkg-0

      - name: 🔄 Restore cache
        uses: https://git.0xmax42.io/actions/cache@v1
        with:
          key: poetry-v1-${{ runner.os }}-${{ hashFiles('poetry.lock') }}
          paths: |
            ~/.cache/pypoetry
            ~/.cache/pip

      - name: Install Poetry
        run: |
          pip install poetry

      - name: Install Project Dependencies
        working-directory: .
        run: |
          poetry install

      - name: Build Package
        working-directory: .
        run: |
          poetry build

      - name: Publish to Gitea Package Registry
        working-directory: .
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          poetry run twine upload --repository-url ${{ secrets.TWINE_URL }} dist/*

      - name: Upload assets
        env:
          GITEA_BASE_URL: https://git.0xmax42.io
          GITEA_TOKEN: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
        run: |
          tea-pkg release-asset maxp/clipcode ${{ github.event.release.tag_name }} ./dist/*.whl
          tea-pkg release-asset maxp/clipcode ${{ github.event.release.tag_name }} ./dist/*.tar.gz

      - name: Run Releases Sync Action
        uses: https://git.0xmax42.io/actions/releases-sync@main
        continue-on-error: true
        with:
          gitea_token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
          gitea_url: https://git.0xmax42.io
          gitea_owner: maxp
          gitea_repo: clipcode
          tag_name: ${{ github.event.release.tag_name }}
          github_token: ${{ secrets.SYNC_GITHUB_TOKEN }}
          github_owner: 0xmax42
          github_repo: clipcode
