name: Auto Changelog & (Release)

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: https://git.0xmax42.io/actions/auto-changelog-release-action@v1
        with:
          token: ${{ secrets.RELEASE_PUBLISH_TOKEN }}
          version_file: pyproject.toml
          version_regex: '^version\s*=\s*"([^"]+)"'
          patch_patterns: |
            ^chore\(deps\)
